import os

class constants(object):
    """description of class"""
    Blank = os.path.join("Images", "blank.png")
    Dot = os.path.join("Images", "dot.png")
    Dotndot = os.path.join("Images", "dotndot.png")
    Sentdex = os.path.join("Images", "sentdex.png")

    Zero_point_1 = os.path.join("Images", "numbers", "0.1.png")
    Zero_point_2 = os.path.join("Images", "numbers", "0.2.png")
    Zero_point_3 = os.path.join("Images", "numbers", "0.3.png")
    Zero_point_4 = os.path.join("Images", "numbers", "0.4.png")
    Zero_point_5 = os.path.join("Images", "numbers", "0.5.png")
    Zero_point_6 = os.path.join("Images", "numbers", "0.6.png")
    Zero_point_7 = os.path.join("Images", "numbers", "0.7.png")
    Zero_point_8 = os.path.join("Images", "numbers", "0.8.png")
    Zero_point_9 = os.path.join("Images", "numbers", "0.9.png")
    One_point_1 = os.path.join("Images", "numbers", "1.1png")
    One_point_2 = os.path.join("Images", "numbers", "1.2.png")
    One_point_3 = os.path.join("Images", "numbers", "1.3.png")
    One_point_4 = os.path.join("Images", "numbers","1.4.png")
    One_point_5 = os.path.join("Images", "numbers","1.5.png")
    One_point_6 = os.path.join("Images", "numbers","1.6.png")
    One_point_7 = os.path.join("Images", "numbers","1.7.png")
    One_point_8 = os.path.join("Images", "numbers","1.8.png")
    One_point_9 = os.path.join("Images", "numbers","1.9.png")
    Two_point_1 = os.path.join("Images", "numbers","2.1.png")
    Two_point_2 = os.path.join("Images", "numbers","2.2.png")
    Two_point_3 = os.path.join("Images", "numbers","2.3.png")
    Two_point_4 = os.path.join("Images", "numbers","2.4.png")
    Two_point_5 = os.path.join("Images", "numbers","2.5.png")
    Two_point_6 = os.path.join("Images", "numbers","2.6.png")
    Two_point_7 = os.path.join("Images", "numbers","2.7.png")
    Two_point_8 = os.path.join("Images", "numbers","2.8.png")
    Two_point_9 = os.path.join("Images", "numbers","2.9.png")
    Three_point_1 = os.path.join("Images", "numbers","3.1.png")
    Three_point_2 = os.path.join("Images", "numbers","3.2.png")
    Three_point_3 = os.path.join("Images", "numbers","3.3.png")
    Three_point_4 = os.path.join("Images", "numbers","3.4.png")
    Three_point_5 = os.path.join("Images", "numbers","3.5.png")
    Three_point_6 = os.path.join("Images", "numbers","3.6.png")
    Three_point_7 = os.path.join("Images", "numbers","3.7.png")
    Three_point_8 = os.path.join("Images", "numbers","3.8.png")
    Three_point_9 = os.path.join("Images", "numbers","3.9.png")
    Four_point_1 = os.path.join("Images", "numbers","4.1.png")
    Four_point_2 = os.path.join("Images", "numbers","4.2.png")
    Four_point_3 = os.path.join("Images", "numbers","4.3.png")
    Four_point_4 = os.path.join("Images", "numbers","4.4.png")
    Four_point_5 = os.path.join("Images", "numbers","4.5.png")
    Four_point_6 = os.path.join("Images", "numbers","4.6.png")
    Four_point_7 = os.path.join("Images", "numbers","4.7.png")
    Four_point_8 = os.path.join("Images", "numbers","4.8.png")
    Four_point_9 = os.path.join("Images", "numbers","4.9.png")
    Five_point_1 = os.path.join("Images", "numbers","5.1.png")
    Five_point_2 = os.path.join("Images", "numbers","5.2.png")
    Five_point_3 = os.path.join("Images", "numbers","5.3.png")
    Five_point_4 = os.path.join("Images", "numbers","5.4.png")
    Five_point_5 = os.path.join("Images", "numbers","5.5.png")
    Five_point_6 = os.path.join("Images", "numbers","5.6.png")
    Five_point_7 = os.path.join("Images", "numbers","5.7.png")
    Five_point_8 = os.path.join("Images", "numbers","5.8.png")
    Five_point_9 = os.path.join("Images", "numbers","5.9.png")
    Six_point_1 = os.path.join("Images", "numbers","6.1.png")
    Six_point_2 = os.path.join("Images", "numbers","6.2.png")
    Six_point_3 = os.path.join("Images", "numbers","6.3.png")
    Six_point_4 = os.path.join("Images", "numbers","6.4.png")
    Six_point_5 = os.path.join("Images", "numbers","6.5.png")
    Six_point_6 = os.path.join("Images", "numbers","6.6.png")
    Six_point_7 = os.path.join("Images", "numbers","6.7.png")
    Six_point_8 = os.path.join("Images", "numbers","6.8.png")
    Six_point_9 = os.path.join("Images", "numbers","6.9.png")
    Seven_point_1 = os.path.join("Images", "numbers","7.1.png")
    Seven_point_2 = os.path.join("Images", "numbers","7.2.png")
    Seven_point_3 = os.path.join("Images", "numbers","7.3.png")
    Seven_point_4 = os.path.join("Images", "numbers","7.4.png")
    Seven_point_5 = os.path.join("Images", "numbers","7.5.png")
    Seven_point_6 = os.path.join("Images", "numbers","7.6.png")
    Seven_point_7 = os.path.join("Images", "numbers","7.7.png")
    Seven_point_8 = os.path.join("Images", "numbers","7.8.png")
    Seven_point_9 = os.path.join("Images", "numbers","7.9.png")
    Eight_point_1 = os.path.join("Images", "numbers","8.1.png")
    Eight_point_2 = os.path.join("Images", "numbers","8.2.png")
    Eight_point_3 = os.path.join("Images", "numbers","8.3.png")
    Eight_point_4 = os.path.join("Images", "numbers","8.4.png")
    Eight_point_5 = os.path.join("Images", "numbers","8.5.png")
    Eight_point_6 = os.path.join("Images", "numbers","8.6.png")
    Eight_point_7 = os.path.join("Images", "numbers","8.7.png")
    Eight_point_8 = os.path.join("Images", "numbers","8.8.png")
    Eight_point_9 = os.path.join("Images", "numbers","8.9.png")
    Nine_point_1 =  os.path.join("Images", "numbers","9.1.png")
    Nine_point_2 =  os.path.join("Images", "numbers","9.2.png")
    Nine_point_3 =  os.path.join("Images", "numbers","9.3.png")
    Nine_point_4 =  os.path.join("Images", "numbers","9.4.png")
    Nine_point_5 =  os.path.join("Images", "numbers","9.5.png")
    Nine_point_6 =  os.path.join("Images", "numbers","9.6.png")
    Nine_point_7 =  os.path.join("Images", "numbers","9.7.png")
    Nine_point_8 =  os.path.join("Images", "numbers","9.8.png")
    Nine_point_9 =  os.path.join("Images", "numbers","9.9.png")





